spring.application.name=voyago-server

# הגדרות חיבור ל-MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/voyago_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=sqlyoni

# הגדרות Hibernate ליצירת טבלאות באופן אוטומטי
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect