spring.application.name=voyago-server

# הפעלת ממשק הניהול של H2
spring.h2.console.enabled=true
# שינוי נתיב הגישה (לפעמים זה עוזר לפתור בעיות 404)
spring.h2.console.path=/h2-console

# הגדרות בסיס הנתונים בזיכרון
spring.datasource.url=jdbc:h2:mem:voyagodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# הגדרות Hibernate ליצירת טבלאות באופן אוטומטי
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect