spring.application.name=voyago-server

# הגדרות חיבור ל-MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/voyago_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=sqlyoni

# הגדרת הדרייבר
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# הגדרות Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.profiles.include=local

gemini.api.key=${GEMINI_API_KEY}